metadata:
  tags:
    cpln/release: cpln-release-elasticsearch

elasticsearch:
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 8.16.2
  
  identity:
    name: elasticsearch

  volume:
    fileSystemType: ext4
    performanceClass: general-purpose-ssd

  config:
    clusterName: "elasticsearch-cluster"
    networkHost: "0.0.0.0"
    nodeStore:
      allowMmap: false
    security:
      enabled: false

  nodes:
    master:
      enabled: true
      replicas: 3
      roles: master
      resources:
        cpu: 2000m
        memory: 4Gi
      volume:
        initialCapacity: 10
        fileSystemType: ext4          # Optional: override default if needed
        performanceClass: general-purpose-ssd  # Optional: override default if needed
    
    data:
      enabled: true
      replicas: 3
      roles: data
      resources:
        cpu: 4000m
        memory: 16Gi
      volume:
        initialCapacity: 20
        fileSystemType: ext4
        performanceClass: general-purpose-ssd
    
    ingest:
      enabled: true
      replicas: 2
      roles: ingest
      resources:
        cpu: 2000m
        memory: 8Gi
      volume:
        initialCapacity: 10
        fileSystemType: ext4
        performanceClass: general-purpose-ssd
    
    coordinator:
      enabled: true
      replicas: 2
      roles: "remote_cluster_client"
      resources:
        cpu: 2000m
        memory: 4Gi
      volume:
        initialCapacity: 10
        fileSystemType: ext4
        performanceClass: general-purpose-ssd

  probes:
    liveness:
      initialDelay: 60
      period: 15
      timeout: 3
    readiness:
      initialDelay: 10
      period: 5
      timeout: 3

  ports:
    - number: 9200
      protocol: http
    - number: 9300
      protocol: tcp