metadata:
  tags:
    cpln/release: cpln-release-elasticsearch

elasticsearch:
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 8.16.2
  
  identity:
    name: elasticsearch

  volume:
    fileSystemType: xfs
    performanceClass: general-purpose-ssd

  config:
    clusterName: "elasticsearch-cluster"
    networkHost: "0.0.0.0"
    nodeStore:
      allowMmap: false
    security:
      enabled: false
    recovery:
      incomingRecoveries: 50
      outgoingRecoveries: 50
      maxBytesPerSec: "2000mb"
    discovery:
      initialMasterNodes: ["es-master-0.es-master", "es-master-1.es-master", "es-master-2.es-master"]
      zen:
        minimumMasterNodes: 2
        pingTimeout: 10s
        joinTimeout: 30s
    cluster:
      initialMasterNodes: ["es-master-0.es-master", "es-master-1.es-master", "es-master-2.es-master"]
      waitForActiveShards: "majority"
    network:
      host: "0.0.0.0"
      publish_host: "${HOSTNAME}.${WORKLOAD_NAME}"
    bootstrap:
      memory_lock: true

  nodes:
    master:
      enabled: true
      replicas: 3
      resources:
        cpu: "3000m"
        memory: "16Gi"
      roles: "master,remote_cluster_client"
      volume:
        fileSystemType: "xfs"
        size: "100Gi"
        initialCapacity: 100
    data:
      enabled: true
      replicas: 3
      resources:
        cpu: "4000m"
        memory: "16Gi"
      roles: "data,data_content,data_hot,data_warm,data_cold"
      volume:
        fileSystemType: "xfs"
        size: "100Gi"
        initialCapacity: 100
    
    ingest:
      enabled: true
      replicas: 2
      roles: "ingest,remote_cluster_client"
      resources:
        cpu: "3000m"
        memory: "16Gi"
      volume:
        initialCapacity: 10
        fileSystemType: xfs
        performanceClass: general-purpose-ssd
    
    coordinator:
      enabled: true
      replicas: 2
      roles: "remote_cluster_client"
      resources:
        cpu: "3000m"
        memory: "16Gi"
      volume:
        initialCapacity: 10
        fileSystemType: xfs
        performanceClass: general-purpose-ssd

  probes:
    liveness:
      initialDelay: 120
      period: 30
      timeout: 5
    readiness:
      initialDelay: 30
      period: 10
      timeout: 5

  ports:
    - number: 9200
      protocol: http
    - number: 9300
      protocol: tcp

  nameSuffix: ""