{{- if and .Values.tracing .Values.tracing.otel }}
---
kind: identity
name: otel-collector-{{ .Values.online_boutique.gvc }}
gvc: {{ .Values.online_boutique.gvc }}
tags: {}
---
kind: secret
name: otel-collector-{{ .Values.online_boutique.gvc }}
description: otel-collector-config
type: opaque
data:
  encoding: plain
  payload: |-
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      filter/httpmetrics:
        spans:
          exclude:
            match_type: strict
            attributes:
              - key: upstream_cluster.name
                value: "inbound|9090||"

      batch:
        timeout: 5s
        send_batch_size: 500

    exporters:
      datadog:
        api: 
          site: ${DD_SITE}
          key: ${DD_API_KEY}

      otlp:
        endpoint: tracing.controlplane:80
        tls:
          insecure: true

    service:
      telemetry:
        logs:
          level: "info"
          
      pipelines:
        traces:
          receivers: [otlp]
          processors: [filter/httpmetrics, batch]
          exporters: [datadog, otlp]
---
kind: secret
name: datadog-config-{{ .Values.online_boutique.gvc }}
description: datadog-config
tags: {}
type: dictionary
data:
  # Do not set DD_API_KEY_VALUE and DD_SITE_VALUE below inside quotation mark
  DD_API_KEY: {{ .Values.tracing.otel.DD_API_KEY }}
  DD_SITE: {{ .Values.tracing.otel.DD_SITE }}
---
kind: policy
name: otel-collector-{{ .Values.online_boutique.gvc }}
tags: {}
origin: default
bindings:
  - permissions:
      - reveal
    principalLinks:
      - //gvc/{{ .Values.online_boutique.gvc }}/identity/otel-collector-{{ .Values.online_boutique.gvc }}
targetKind: secret
targetLinks:
  - //secret/datadog-config-{{ .Values.online_boutique.gvc }}
  - //secret/otel-collector-{{ .Values.online_boutique.gvc }}
---
kind: workload
name: otel-collector
gvc: {{ .Values.online_boutique.gvc }}
description: otel-collector
spec:
  type: standard
  containers:
    - name: otel-collector
      args:
        - '--config=/etc/otel-collector-config.yaml'
      cpu: {{ .Values.tracing.otel.cpu }}
      env:
        - name: DD_API_KEY
          value: 'cpln://secret/datadog-config-{{ .Values.online_boutique.gvc }}.DD_API_KEY'
        - name: DD_SITE
          value: 'cpln://secret/datadog-config-{{ .Values.online_boutique.gvc }}.DD_SITE'
      image: {{ .Values.tracing.image }}
      inheritEnv: false
      memory: {{ .Values.tracing.otel.memory }}
      ports:
        - number: 4317
          protocol: grpc
        - number: 4318
          protocol: http
      volumes:
        - path: /etc/otel-collector-config.yaml
          recoveryPolicy: retain
          uri: 'cpln://secret/otel-collector-{{ .Values.online_boutique.gvc }}'
  defaultOptions:
    autoscaling:
      maxConcurrency: 0
      maxScale: 1
      metric: cpu
      minScale: 1
      scaleToZeroDelay: 300
      target: 95
    capacityAI: false
    debug: false
    suspend: false
    timeoutSeconds: 5
  firewallConfig:
    external:
      inboundAllowCIDR: []
      outboundAllowCIDR:
        - 0.0.0.0/0
      outboundAllowHostname: []
      outboundAllowPort: []
    internal:
      inboundAllowType: same-gvc
      inboundAllowWorkload: []
  identityLink: //identity/otel-collector-{{ .Values.online_boutique.gvc }}
  localOptions: []
  supportDynamicTags: false
{{- end }}