# Default values for mongodb-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mongodb:
  name: mongodb4-new
  image: mongo:4.4.29 # Choose an image of a supported version https://hub.docker.com/_/mongo/tags
  replicas: 3
  port: 27017
  memory: 500Mi # EX. 3000Mi = 3Gi
  cpu: 1000m # vCPU or milicores with; EX. 1.5 = 1500m
  replSetName: myReplicaSet
  volume:
    initialCapacity: 25 # In Gigabytes. For high-throughput-ssd minimum is '1000'
    fileSystemType: xfs # ext4 / xfs
    performanceClass: general-purpose-ssd # high-throughput-ssd / general-purpose-ssd
  snapshots:
    createFinalSnapshot: 'true'
    retentionDuration: 7d
    schedule: '0 1 * * *'
  # To disable all traffic, comment out the corresponding rule. Docs: https://docs.controlplane.com/concepts/security#firewall
  firewall:
    internal_inboundAllowType: "same-org" # Options: same-org / same-gvc(Recommended)
    # external_inboundAllowCIDR: 0.0.0.0/0 # Provide a comma-separated list
    external_outboundAllowCIDR: "0.0.0.0/0" # Provide a comma-separated list