kind: policy
name: elasticsearch-policy-{{ .Values.cpln.gvc }}{{ .Values.elasticsearch.nameSuffix }}
origin: default
bindings:
  - permissions:
      - reveal
    principalLinks:
      - //gvc/{{ .Values.cpln.gvc }}/identity/{{ .Values.elasticsearch.identity.name }}
targetKind: secret
targetLinks:
  - //secret/elasticsearch-config-{{ .Values.cpln.gvc }}{{ .Values.elasticsearch.nameSuffix }}
  - //secret/elasticsearch-init-{{ .Values.cpln.gvc }}{{ .Values.elasticsearch.nameSuffix }}
