apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-with-metrics
  namespace: cnpg-freetier
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-cluster-with-metrics
  namespace: cnpg-freetier
spec:
  cluster:
    name: cluster-with-metrics
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-with-metrics
  namespace: cnpg-freetier
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": cluster-with-metrics
  podMetricsEndpoints:
  - port: metrics