apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-with-metrics-3
  namespace: cnpg-freetier
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "300m"
    limits:
      memory: "384Mi"
      cpu: "400m"

  # superuserSecret:
  #   name: superuser-secret ??? Or disable it all together / or just don't show it 

  bootstrap:
    initdb:
      database: igor
      owner: igor
      secret:
        name: igor-basic-auth
---
apiVersion: v1
data:
  password: dG9wc2VjcmV0
  username: aWdvcg==
kind: Secret
metadata:
  name: igor-basic-auth
type: kubernetes.io/basic-auth
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-with-metrics-2
  namespace: cnpg-freetier
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": cluster-with-metrics-2
  podMetricsEndpoints:
  - port: metrics